[package]
name = "speenoza"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.9.1"
ndarray-csv = "0.5.1"
csv = "1.1.6"
itertools = "0.10.3"